#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

declare -a APRX_SERVICE_FILES

# Test if there are any .aprx files in the index
for filepath in $(git diff --cached --name-only --diff-filter=M)
do
	test -z $(echo $filepath | gawk '/aprx$/') || APRX_SERVICE_FILES+=($filepath);
	test -z $(echo $filepath | gawk '/mapx$/') || MAPX_FILES+=($filepath);
done
if [ ${#APRX_SERVICE_FILES[@]} -gt 0 ]; then
  for f in $APRX_SERVICE_FILES
  do
    sh $(git rev-parse --git-dir)/export-map.sh $f
	if [ $? -eq 9 ]; then
		echo "Removing from commit"
		if ! [ ${#MAPX_SERVICE_FILES[@]} -gt 0 ]; then #only reset aprx if there is no exported file in the commit either
			git reset -q $f 
		fi
		STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM) #check if there is no more files to commit, if so quit
		if [ -z "$STAGED_FILES" ]; then
			exit 1
		fi
	fi
    if [ $? -ne 0 ]; then
		echo 'Error in export'
		exit 1
	fi
  done
fi

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true
message="COMMIT FAILED: "

for FILE in $STAGED_FILES
do
  if (grep -F '#DEV' $FILE) || (grep -F '//DEV' $FILE); then
  PASS=false
  message+=" Looks like there are some DEV comments to clear.\n"
  fi
  if (grep -F 'debugger;' $FILE) || (grep -F 'console.log(' $FILE) || (grep -F 'print(' $FILE); then
  PASS=false
  message+=" Looks like there are some debugger statements to clear.\n"
  fi
done

if ! $PASS; then
  printf message
  exit 1
fi

exit $?
