SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE FUNCTION xxxxx.Get_Source_CL_From_View
(	
	@viewname varchar(255)
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT VIEW_SCHEMA, VIEW_NAME, ucj.COLUMN_NAME AS 'VIEW_COLUMN', ucj.TABLE_SCHEMA AS 'COLUMN_SOURCE_TABLE_SCHEMA', ucj.TABLE_NAME AS 'COLUMN_SOURCE_TABLE_NAME', ccu.TABLE_SCHEMA AS 'CL_SCHEMA', ccu.TABLE_NAME AS 'CL_TABLE', ccu.COLUMN_NAME AS 'CL_COLUMN' FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu
    JOIN (SELECT CONSTRAINT_SCHEMA, rc.CONSTRAINT_NAME, UNIQUE_CONSTRAINT_SCHEMA, UNIQUE_CONSTRAINT_NAME, VIEW_SCHEMA, VIEW_NAME, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc 
        JOIN (SELECT CONSTRAINT_NAME, VIEW_SCHEMA, VIEW_NAME, vcu.TABLE_SCHEMA, vcu.TABLE_NAME, vcu.COLUMN_NAME FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE kcu 
            JOIN (SELECT * FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE WHERE VIEW_NAME = @viewname AND COLUMN_NAME LIKE '%CL') vcu 
                ON kcu.COLUMN_NAME = vcu.COLUMN_NAME AND kcu.TABLE_NAME = vcu.TABLE_NAME) cj 
            ON rc.CONSTRAINT_NAME = cj.CONSTRAINT_NAME) ucj 
        ON ccu.CONSTRAINT_NAME = ucj.UNIQUE_CONSTRAINT_NAME
)
GO
