#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

declare -a APRX_SERVICE_FILES
declare -a MAPX_FILES

# Test if there are any .aprx files in the index
for filepath in $(git diff --cached --name-only --diff-filter=M)
do
	test -z $(echo $filepath | gawk '/aprx$/') || APRX_SERVICE_FILES+=($filepath);
	test -z $(echo $filepath | gawk '/mapx$/') || MAPX_FILES+=($filepath);
  test -z $(echo $filepath | gawk '/config[.]py$/') || checkConfigEnv $filepath;
  test -z $(echo $filepath | gawk '/setEnvironment[.]py$/') || checkConfigEnv $filepath;
done
if [ ${#APRX_SERVICE_FILES[@]} -gt 0 ] && [ -e $(git rev-parse --show-toplevel)/.githooks/export-map.sh ]; then
  for f in ${APRX_SERVICE_FILES[@]}
  do
    echo "Aprx file found: $f"
    sh $(git rev-parse --show-toplevel)/.githooks/export-map.sh $f
    rc=$?
    if [ $rc -eq 9 ]; then
      echo "No detected change from previous map export."
      hasExport=false
      for mf in ${MAPX_FILES[@]}
      do
        if [ "$mf" == "${f%.aprx}.mapx" ]; then
        echo "Current export provided. Will continue with adding this map to commit."
        hasExport=true
        fi
      done
      if [ "$hasExport" = false ]; then #only reset aprx on an non-diff if there is no matching exported file left in the commit
        echo "No export provided. Removing aprx from commit."
        git reset $f 
      fi
    elif [ $rc -ne 0 ]; then
		  echo 'Error in export'
	  fi
    continue
  done
fi
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM) #check if there are no more files to commit, if so quit
if [ ${#STAGED_FILES[@]} -eq 0 ]; then
  echo "No files left to commit. Aborting commit."
  exit 1
fi

if [ ${#STAGED_FILES[@]} -eq 0 ]; then
  exit 0
fi

PASS=true
message="COMMIT FAILED: "

#The following is optional stuff, just checking for dev comments

for FILE in $STAGED_FILES
do
  if (grep -FHn '#DEV' $FILE) || (grep -F '//DEV' $FILE); then
  PASS=false
  printf "Looks like there are some DEV comments to clear.\n"
  fi
  if (grep -FHn 'debugger;' $FILE); then
  PASS=false
  printf " Looks like there are some debugger statements to clear.\n"
  fi
done

if ! $PASS; then
  exit 1
fi

exit $?
